import { useEffect, useState } from "react";

/**
 * The landing page.
 *
 * The hero is the product's own thesis, running: one photograph, and the
 * copy on it cycling through seven scripts while the picture underneath
 * never changes. That is literally what the system does, so showing it beats
 * any sentence describing it — and it is the one thing on this page that
 * could not be lifted from another product's site.
 *
 * Those are real creatives, generated by the pipeline and exported to
 * public/showcase. Nothing here is a mockup.
 */

const SHOWCASE = [
  { key: "en", label: "English", native: "English", bcp47: "en" },
  { key: "hi", label: "Hindi", native: "हिन्दी", bcp47: "hi" },
  { key: "hi-Latn", label: "Hinglish", native: "Hinglish", bcp47: "hi-Latn" },
  { key: "mr", label: "Marathi", native: "मराठी", bcp47: "mr" },
  { key: "bn", label: "Bengali", native: "বাংলা", bcp47: "bn" },
  { key: "ta", label: "Tamil", native: "தமிழ்", bcp47: "ta" },
  { key: "te", label: "Telugu", native: "తెలుగు", bcp47: "te" },
];

const STEPS = [
  {
    n: "01",
    title: "You write one line",
    body:
      "What you sell, in plain words. A model turns it into a brief — what " +
      "to photograph, the proposition, the occasion, and which part of the " +
      "frame to keep clear for the copy.",
  },
  {
    n: "02",
    title: "One image is generated",
    body:
      "Deliberately text-free. This is the only step that costs anything, " +
      "and it happens once — however many languages you asked for.",
  },
  {
    n: "03",
    title: "Every language is typeset onto it",
    body:
      "Not drawn by the model. Set in a real typesetting engine, so " +
      "conjuncts and matras are correct — then composited with your logo " +
      "inside Instagram's safe zones.",
  },
];

const REFUSALS = [
  {
    title: "It will not invent a claim",
    body:
      "Prices, discounts and guarantees exist only if you typed them. A " +
      "model that helpfully adds “50% off” has written a false advertisement.",
  },
  {
    title: "It will not draw your logo",
    body:
      "A generated logo is a wrong logo. Yours is composited from the real " +
      "file, with the light or dark version chosen by measuring the pixels " +
      "behind it.",
  },
  {
    title: "It will not redesign your building",
    body:
      "Upload a photo of a real property and it is restaged, never " +
      "reinvented. The result is measured against your original, and drift " +
      "is flagged before anyone publishes it.",
  },
];

export default function Landing({ onStart }) {
  const [index, setIndex] = useState(0);
  const [paused, setPaused] = useState(false);

  // The hero cycles by itself, because the point is comprehension before
  // interaction: a visitor should understand the product without clicking.
  // It stops the moment they take over, and honours reduced-motion.
  useEffect(() => {
    if (paused) return;
    const reduce = window.matchMedia?.("(prefers-reduced-motion: reduce)").matches;
    if (reduce) return;
    const timer = setInterval(
      () => setIndex((i) => (i + 1) % SHOWCASE.length),
      2600
    );
    return () => clearInterval(timer);
  }, [paused]);

  const current = SHOWCASE[index];

  return (
    <div className="landing">
      <header className="lp-nav">
        <div className="lp-mark">
          Brandly<span className="ai">AI</span>
        </div>
        <span className="lp-spacer" />
        <a className="lp-link"
           href="https://github.com/rudrakshxgupta/marketing-campaign-generator">
          Source
        </a>
        <button className="lp-cta small" onClick={onStart}>Open the studio</button>
      </header>

      <section className="lp-hero">
        <div className="lp-hero-copy">
          <p className="lp-eyebrow">Built on Microsoft AI Foundry</p>
          <h1>
            One line in.<br />
            Seven languages out.
          </h1>
          <p className="lp-lede">
            Describe what you sell. Get Instagram-ready campaign creatives in
            English, Hindi, Hinglish, Marathi, Bengali, Tamil and Telugu — from
            a single image generation.
          </p>
          <div className="lp-actions">
            <button className="lp-cta" onClick={onStart}>Open the studio</button>
            <span className="lp-note">No sign-up. Runs on your own machine.</span>
          </div>

          <dl className="lp-stats">
            <div><dt>1 → 7</dt><dd>image calls to finished creatives</dd></div>
            <div><dt>7</dt><dd>languages, typeset not drawn</dd></div>
            <div><dt>0</dt><dd>extra cost for the next language</dd></div>
          </dl>
        </div>

        <div className="lp-hero-art"
             onMouseEnter={() => setPaused(true)}
             onMouseLeave={() => setPaused(false)}>
          <div className="lp-frame">
            {SHOWCASE.map((item, i) => (
              <img
                key={item.key}
                src={`/showcase/${item.key}.jpg`}
                alt={`The same campaign, set in ${item.label}`}
                className={i === index ? "on" : ""}
                loading={i === 0 ? "eager" : "lazy"}
              />
            ))}
          </div>

          {/* The caption is the proof: the photograph is constant, only the
              language changes. Saying so beside it makes the point explicit
              for anyone who reads one script and not the others. */}
          <p className="lp-frame-note">
            Same photograph. Same generation.{" "}
            <b lang={current.bcp47}>{current.native}</b>.
          </p>

          <div className="lp-switch" role="tablist" aria-label="Language">
            {SHOWCASE.map((item, i) => (
              <button
                key={item.key}
                role="tab"
                aria-selected={i === index}
                lang={item.bcp47}
                onClick={() => { setIndex(i); setPaused(true); }}
              >
                {item.native}
              </button>
            ))}
          </div>
        </div>
      </section>

      <section className="lp-band">
        <p>
          A Diwali line translated into Bengali is still a Diwali line — when
          the campaign that audience responds to is{" "}
          <b lang="bn">Durga Puja</b>.
        </p>
        <span>
          So the copy is authored in each language from one strategy, not
          translated. The festival changes, not just the words.
        </span>
      </section>

      <section className="lp-section">
        <h2>How it works</h2>
        <ol className="lp-steps">
          {STEPS.map((step) => (
            <li key={step.n}>
              <span className="lp-step-n">{step.n}</span>
              <h3>{step.title}</h3>
              <p>{step.body}</p>
            </li>
          ))}
        </ol>
      </section>

      <section className="lp-section">
        <h2>What it refuses to do</h2>
        <p className="lp-sub">
          Most of the engineering here went into the things it will not
          generate.
        </p>
        <div className="lp-refusals">
          {REFUSALS.map((item) => (
            <article key={item.title}>
              <h3>{item.title}</h3>
              <p>{item.body}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="lp-end">
        <h2>Ready when you are.</h2>
        <p>
          The studio runs locally. With no credentials it still works
          end-to-end against placeholder imagery, so you can see the whole
          pipeline before spending anything.
        </p>
        <button className="lp-cta" onClick={onStart}>Open the studio</button>
      </section>

      <footer className="lp-foot">
        <span>BrandlyAI — Social Media Content Generation in Multiple Languages</span>
        <span className="lp-spacer" />
        <span>FLUX.2-pro · GPT-5-mini · Microsoft AI Foundry</span>
      </footer>
    </div>
  );
}
